mungstagram/take_backend

Dockerfile
- EC2에서 Docker ps -a 로 Docker의 상태를 확인해 본 결과 Exited(1) 발생.
- DokcerFile 수정
- dataSource.ts가 도커에 반영되지 않은것 수정
- #18
=> 18 [💚] CI/CD Fix Exited(1) 에러 발생.

src/app.module.ts, src/common/middleware/logger.middleware.ts
- Reqeust 요청을 Logging 하는 Midleware 작성
- 작업사항
- 변경사항
- #14
=> 14 [✨] Logging Middleware 만들기

src/auth/auth.controller.ts, src/users/users.controller.ts
- 협업을 위한 Swagger 작성
- 로그인 , 회원가입 Swagger 작성
- 변경사항
- #23
=> 23 [📝] Swagger 작성하기

src/app.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/auth/jwt/jwt.guard.ts, src/auth/jwt/jwt.payload.dto.ts, src/auth/jwt/jwt.strategy.ts, src/common/dacorators/get.payload.decorator.ts
- JwtGuard 만들기
- AccessToken 인가 작업
- 변경사항
- #25
=> 25 [✨] JwtGuard 만들기

src/posts/controllers/posts.controller.ts, src/posts/posts.module.ts, src/posts/services/posts.service.ts
- 전체 게시글 조회 api 제작
- 전체 게시글 조회 api 제작 완료
- 유저 연결 필요
- 해시태그 기능 추가 필요
- 없음
- #28
=> 28[✨] post get api

src/app.controller.ts, src/auth/auth.module.ts, src/auth/jwt/jwt.guard.ts, src/database/seeds/create-inital-data.ts, src/entities/Posts.ts, src/posts/controllers/posts.controller.ts, src/posts/dto/postscreate.request.dto.ts, src/posts/posts.module.ts, src/posts/services/posts.service.ts
- 상세 게시글 조회 api 제작
- 게시글 상세 조회 기능 추
- 없음
- #28
=> 28[✨] post get one post api

src/comments/comments.controller.ts
-  comments.cotroller.ts 오타 수정
- JwtAuthGard - > JwtAuthGuard
- 변경사항
- #36
=> 36 [✏️] comments.cotroller.ts 오타 수정

Dockerfile
- Dockerfile 의 Node 버전이 작업 환경과 달라서 에러 발생함.
- Dockerfile 의 노드 버전을 18 버전으로 변경함
- Dockerfile
- #39
=> 39 [💚] Dockerfile의 Node 버전 이슈

package.json, src/auth/auth.service.spec.ts
- 게시글 65,000 건 조회시 OOP 발생하여 메모리 추가 할당
-     "start:prod": "node --max-old-space-size=12000 dist/src/main.js",
- 변경사항
- #47
=> 47 [🔨] 스크립트 수정

src/app.module.ts, src/entities/Todos.ts, src/entities/Users.ts, src/todos/dtos/todo.request.dto.ts, src/todos/todos.controller.ts, src/todos/todos.module.ts, src/todos/todos.service.spec.ts, src/todos/todos.service.ts, src/users/dtos/signup.request.dto.ts, src/users/users.service.ts
- todolist api
- todolist crud api + testcode 일부
- signup swagger example 수정
- #50
=> 50 [✨] Todo List API

src/app.module.ts, src/database/seeds/create-inital-data.ts, src/dogs/dogs.controller.ts, src/dogs/dogs.module.ts, src/dogs/dogs.service.ts, src/dogs/dtos/dog.request.dto.ts, src/entities/Dogs.ts, src/entities/Users.ts, src/posts/services/posts.service.ts, src/profile/profile.controller.ts, src/profile/profile.module.ts, src/profile/profile.service.ts, src/users/dtos/signup.request.dto.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts
- dogs crud 및 api 수정
- home api 추가
- profile api 추가
- dogs 엔티티 수정, seed data 수정, dto 수정
- home에서 user, dogs data 조회 api 추가
- profile 조회 api 추가
- dogs 엔티티, seed data, dto
- #49
=> 49 [✨] profile and user's home api

src/app.module.ts, src/dogs/dogs.module.ts, src/users/dtos/signup.request.dto.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.spec.ts, src/users/users.service.ts
- user service 수정
- user service 부분에 조회, 수정 기능 삭제
- profile 부분으로 해당 기능 넘어갈 예정
- user service 가입 외의 데이터 삭제
- #49
=> 49 [🔥]user service에 만들어둔 조회 수정 기능 삭제

src/users/dtos/user.reqeust.dto.ts, src/users/users.controller.ts, src/users/users.service.ts
- 이메일 , 닉네임 중복검사 및 유효성 검사 API
- 회원 가입때 사용할 이메일 , 닉네임 중복검사 및 유효성 검사 API
- 변경사항
- #55
=> 55 [✨] Email, Nickname 중복 검사 및 유효성 검사 API

src/todos/todos.service.ts
- 존재하지 않은 투두리스트 삭제시 에러발생하지 않은 버그 수정
- 존재하지 않은 투두리스트 삭제시 에러발생하지 않은 버그 수정
- 
- #50
=> 50 [🐛] Fix TodoList 삭제 API

src/posts/controllers/posts.controller.ts, src/posts/dto/postscreate.request.dto.ts, src/posts/services/posts.service.ts, src/profile/profile.service.ts
- 게시글 조회 swagger 업데이트
- 게시글 조회 swagger 업데이트
- 게시글 조회 swagger 사용 가능하게 변경
- #49
=> 49 [🔧] swagger updated

src/app.module.ts, src/dms/dms.controller.ts, src/dms/dms.module.ts, src/dms/dms.service.spec.ts, src/dms/dms.service.ts, src/dms/dto/popup.chatroom.dto.ts, src/dms/dto/update-dm.dto.ts, src/dms/entities/dm.entity.ts, src/events/events.gateway.spec.ts, src/events/events.gateway.ts, src/events/events.module.ts, src/models/ChatRoom.ts, src/models/Chattings.ts
- DM 기능 구현
- dms API 작성, Socket.IO 를 이용한 실시간 데이터 통신 구현
- .env MongoDB 연결
-  #57
=> 57 [✨] DM 기능 구현 

src/database/seeds/create-inital-data.ts, src/entities/Dogs.ts, src/entities/Posts.ts, src/entities/Users.ts, src/helper/fileupload.helper.ts, src/helper/get.file.url.helper.ts, src/posts/posts.module.ts, src/posts/services/posts.service.ts
- DB구조 변경에 따른 PostAPI 의 코드 리팩토링
- DB구조 변경에 따른 PostAPI 의 코드 리팩토링
- DB구조 변경에 따른 PostAPI 의 코드 리팩토링
- #67
=> 67 [♻️] Post Api 리팩토링

src/app.module.ts, src/database/seeds/create-inital-data.ts, src/helper/filedelete.helper.ts, src/posts/services/posts.service.ts, src/profile/profile.module.ts, src/profile/profile.service.ts
- 프로필 CRU 부분 전체 수정
- 프로필, 홈화면, 홈화면 수정
- profile controller, modul, service 수정, seed data 수정
- #67
=> 67 [✨] profile CRU 부분 전체 수정

src/dogs/dogs.controller.ts, src/dogs/dogs.module.ts, src/dogs/dogs.service.ts, src/dogs/dtos/dog.request.dto.ts, src/posts/controllers/posts.controller.ts
- dog create 기능 및 결과 수정
- dog create에 사진 업로드 가능, 결과값 수정
- dog create에 사진 업로드 가능, 결과값 수정
- #49
=> 67 [♻️] dog create 기능 및 결과 수정

src/auth/auth.module.ts, src/posts/services/posts.service.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts
- user_detail 조회 api 생성, posts typeorm 수정
- user_detail 조회 api 생성, posts typeorm 수정
- posts typeorm 수정
- #73
=> 73 [✨] user_detail 조회 api 생성, posts typeorm 수정

src/todos/dtos/todo.request.dto.ts, src/todos/todos.service.ts, src/users/users.service.ts
- todos 결과값 수정
- todos 결과값 수정
- todos 결과값 수정
- #67
=> 67 [♻️] todos 결과값 수정

src/auth/auth.service.spec.ts, src/comments/comments.service.spec.ts, src/todos/todos.service.spec.ts, src/users/users.service.spec.ts
-테스트 코드 수정
- 테스트 코드 수정
- 테스트 코드 수정
- #78
=> 67 [✅] 테스트 코드 수정

Dockerfile
- Docker FIle 수정
- DockerFIle에 mongoDataSource.ts COPY 하도록 추가
- DockerFIle
- #77
=> 77 [📝] DockerFile 수정

src/entities/Users.ts, src/searches/searches.service.ts, src/users/users.controller.ts
- 프론트엔드 전송 데이터 수정
- 프론트엔드 전송 데이터 수정
- 프론트엔드 전송 데이터 수정
- #81
=> 81 [🩹] 프론트엔드 전송 데이터 수정

src/todos/dtos/todo.request.dto.ts, src/todos/todos.controller.ts, src/todos/todos.service.spec.ts
- Todo Create시 done 값이 자동으로 false로 입력되게 수정
- 코드 수정에 따른 TestCode 수정
- 작업사항
- 변경사항
- #81
=> 81 [🩹] Todos Create 수정

src/dms/dms.controller.ts, src/dms/dms.module.ts, src/dms/dms.service.ts, src/dms/entities/dm.entity.ts, src/entities/mongo/ChatRoom.ts, src/events/events.gateway.ts, src/events/events.module.ts, src/events/socket.jwt.guard.ts
- DM DB 구조 변경 및 리팩토링
- DM DB 구조 변경 및 리팩토링
- 변경사항
- #57
=> 57 [♻️] DM DB 구조 변경 및 리팩토링

src/auth/auth.module.ts, src/events/events.gateway.ts, src/events/events.module.ts, src/profile/profile.controller.ts, src/profile/profile.service.ts, src/searches/searches.controller.ts, src/searches/searches.module.ts, src/searches/searches.service.ts, src/users/users.controller.ts, src/users/users.service.ts
- db 변경에 따른 코드 리팩토링 및 에러처리
- db 변경에 따른 코드 리팩토링 및 에러처리
- db 변경에 따른 코드 리팩토링 및 에러처리
- #81
=> 81 [♻️] db 변경에 따른 코드 리팩토링 및 에러처리

src/events/events.gateway.ts
- 채팅방에 접속했을때 마지막 채팅의 내역도 보내도록 구현
- 채팅방에 접속했을때 마지막 채팅의 내역도 보내도록 구현
- 변경사항
- #57
=> 57 [✨] 채팅방 마지막 채팅 내역 추가

src/events/events.gateway.ts
- user Profile Image , timeGap , nickname 추가
- user Profile Image , timeGap , nickname 추가
- 변경사항
- #57
=> 57 [✨] 마지막 채팅 내역에 user의 Profile 사진 추가

src/events/events.gateway.ts
- DMList 입장시 에러 발생한는것 수정
- 작업사항
- 변경사항
- #57
=> 57 [🐛] GateWay try로 감쌈

src/events/events.gateway.ts
- DM 발송시 발신자에게도 emit 가도록 수정
- DM 발송시 발신자에게도 emit 가도록 수정
- 변경사항
- #57
=> 57 [🩹] Fix DM 발송시 emit 추가

src/helper/timegap.helper.ts, src/posts/services/posts.service.ts
- 댓글 프로필 이미지 추가, time gap 수정
- 댓글 프로필 이미지 추가, time gap 수정
- 댓글 프로필 이미지 추가, time gap 수정
- #81
=> ♻️ [81] 댓글 프로필 이미지 추가, time gap 수정

src/posts/services/posts.service.ts
- 게시글 전체 조회시 profileImage 수정
- 게시글 전체 조회시 profileImage 수정
- 게시글 전체 조회시 profileImage 수정
- #81
=> 🔧 [81] 게시글 전체 조회시 profileImage 수정

src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/dtos/kakao.request.dto.ts, src/comments/comments.service.ts, src/dms/dms.service.ts, src/dms/dto/popup.chatroom.dto.ts, src/dogs/dogs.controller.ts, src/dogs/dtos/dog.request.dto.ts, src/entities/Users.ts, src/users/dtos/signup.request.dto.ts, src/users/dtos/user.reqeust.dto.ts, src/users/users.service.ts
- Social Login API 리팩토링
- Social Login API 리팩토링
- 변경사항
- #21
=> 21 [✨] Social Login API 리팩토링

src/todos/todos.service.spec.ts
- todos 테스트 코드 수정
- todos 테스트 코드 수정
- todos 테스트 코드 수정
- #102
=> 🔧 [102] todos 테스트 코드 수정

src/profile/profile.service.ts
- 프로필 조회 에러 수정
- 프로필 조회 에러 수정
- 프로필 조회 에러 수정
- #102
=> 102 [🔧] 프로필 조회 에러 수정

src/auth/auth.service.ts, src/events/events.gateway.ts, src/searches/searches.service.ts, src/todos/todos.service.spec.ts, src/todos/todos.service.spec2.ts
- DM 보낼떄 sender, receiver가 정상적으로 보내지지 않는 버그 수정, Search contentURL 없는 유저 검색시 에러 발생하는 버그 수정
- DM 보낼떄 sender, receiver가 정상적으로 보내지지 않는 버그 수정, Search contentURL 없는 유저 검색시 에러 발생하는 버그 수정
- 변경사항
- #81
=> 81 [🩹] 에러처리 및 swagger 수정

src/auth/auth.service.ts, src/searches/searches.controller.ts, src/searches/searches.service.ts, src/users/users.service.ts
-  닉네임 제한 숫자 변경
- 닉네임 제한 숫자 변경
-  닉네임 제한 숫자 변경
- #102
=> 102 [🔧] 닉네임 제한 숫자 변경

src/events/events.gateway.ts
- 채팅 웹소캣 프로필 없는 경우 에러처리
- 채팅 웹소캣 프로필 없는 경우 에러처리
- 채팅 웹소캣 프로필 없는 경우 에러처리
- #81
=> 81 [🐛] 채팅 웹소캣 프로필 없는 경우 에러처리

src/helper/fileupload.helper.ts
- 강아지등록, 포스트작성 시 이미지 없을 경우 에러처리
- 강아지등록, 포스트작성 시 이미지 없을 경우 에러처리
- 강아지등록, 포스트작성 시 이미지 없을 경우 에러처리
- #81
=> 81 [🐛] 강아지등록, 포스트작성 시 이미지 없을 경우 에러처리

src/profile/profile.service.ts
- 닉네임 글자수 제한 에러처리
- 
- 닉네임 글자수 제한 에러처리
- 닉네임 글자수 제한 에러처리
- #81
=> 81 [🐛] 닉네임 글자수 제한 에러처리

src/app.controller.ts, src/entities/Comments.ts, src/entities/Dogs.ts, src/entities/PostFiles.ts, src/entities/PostLikes.ts, src/entities/Posts.ts, src/entities/Todos.ts, src/entities/Tokens.ts, src/entities/Users.ts, src/users/users.controller.ts, src/users/users.service.ts
- Entity Cascade 설정 및 회원탈퇴 API 구현
- Entity Cascade 설정 및 회원탈퇴 API 구현
- users service , controller , Entity
- #115
=> 115 [✨] 회원탈퇴 기능

src/app.controller.ts, src/helper/fileupload.helper.ts
- cloudfront 적용 및 에러 분기처리
- cloudfront 적용 및 에러 분기처리
- cloudfront 적용 및 에러 분기처리
- #81
=> 81 [🩹] cloudfront 적용 및 에러 분기처리

src/profile/profile.service.ts
- 프로필 수정 시 보유 강아지 숫자 반환
- 
- 프로필 수정 시 보유 강아지 숫자 반환
- 프로필 수정 시 보유 강아지 숫자 반환
- #81
=> 81 [🩹] 프로필 수정 시 보유 강아지 숫자 반환

src/dogs/dogs.service.ts
- 강아지 생성시 대표여부 추가
- 강아지 생성시 대표여부 추가
- 강아지 생성시 대표여부 추가
- #81
=> 81 [🩹] 강아지 생성시 대표여부 추가

src/common/middleware/logger.middleware.ts, src/dogs/dogs.controller.ts, src/dogs/dogs.service.ts, src/dogs/dtos/dog.request.dto.ts
-  Dog Delete API 구현 완료
-  Dog Delete API 구현 완료
- loggermiddleware 수정
- logger middleware
- #128
=> 128 [✨] Dog Delete API 구현

.github/workflows/releaseTag.yaml
- main에 pr시 자동으로 버전태그 달아주는 gitaction 추가
- main에 pr시 자동으로 버전태그 달아주는 gitaction 추가
- 변경사항
- #130
=> 130 [✨] 오토태깅 기능 추가

src/common/middleware/logger.middleware.ts, src/dms/dms.service.ts, src/events/events.gateway.ts, src/users/users.service.ts
- DM중 상대가 나가면 DM 이 보내지지 않는 버그 수정
- DM중 상대가 나가면 DM 이 보내지지 않는 버그 수정
- 변경사항
- #135
=> 135 [:bug:] Fix DM 채팅 안되는 버그

src/events/events.gateway.ts
- DM중 상대가 나가면 대화가 되지 않는 버그 수정
- DM중 상대가 나가면 대화가 되지 않는 버그 수정
- 변경사항
- #135
=> 135 [🐛] DM 버그 픽스
